### ISSUE TITLE
Unable to use newer versions of megaparsec

### ISSUE THREAD

**Issue by srid** [obsidiansystems/obelisk#111]
Projects cannot use newer versions of megaparsec even when specifically pinned in the project's default.nix. This appears to be because obelisk's default.nix overrides it for some reason:

```
$ ag -C 1 megaparsec default.nix
91-            '';
92:          })).override { megaparsec = super.megaparsec_6_1_1; };
93-    algebraic-graphs =
```

**Comment by ryantrinkle** [comment]
Yeah, we should be applying this override *before* the user's overrides (unless of course we can get rid of it completely).

**Comment by eskimor** [comment]
This is only a local override for `modern-uri`. The user's overrides already happen last! But, I thought I was able to reproduce your problem at first: If all you are doing is adding the override to your default.nix and then check with `ghc-pkg list | grep megaparsec` you will in fact only see megaparsec-6.1.1:

```
robert@xps13 ~/workbench/obelisk-test (master*) $ nix-shell ./default.nix -A shells.ghc
robert@xps13 ~/workbench/obelisk-test (master*) $ ghc-pkg list | grep megaparsec
    megaparsec-6.1.1
```

The reason is, nix is lazy! You have to add the dependency to your cabal file, for nix to install it. Simply put megaparsec to your build-depends section in frontend/frontend.cabal for example and you will see the following:

```
robert@xps13 ~/workbench/obelisk-test (master*) $ nix-shell ./default.nix -A shells.ghc
robert@xps13 ~/workbench/obelisk-test (master*) $ ghc-pkg list | grep megaparsec
    megaparsec-6.1.1
    megaparsec-5.3.1
```

if you have not overridden megaparsec yet, otherwise you will see your overridden version of course. You can verify that cabal is picking the right version by adding appropriate version bounds - cabal will pick yours!

**Comment by eskimor** [comment]
But, btw. the newest megaparsec (6.5.0) won't build without updating some dependencies too:

```
Setup: Encountered missing dependencies:
parser-combinators >=0.4 && <1.0
```

**Comment by lpsmith** [comment]
It would appear that this issue has been long since resolved,  on or around https://github.com/obsidiansystems/obelisk/commit/169972db143da3dd3ae084939145d94327cc9ce5
