### ISSUE TITLE
Skip Tests for dependencies of obelisk cmd / run

### ISSUE THREAD

**Issue by mjrussell** [obsidiansystems/obelisk#186]
Installing into a fresh nix install on MacOSX I only got some amount of binary caching. It seemed like obelisk was building `command` and all sub commands such as `ob run` with testing (no `pkgs.haskell.lib.dontCheck`). This is especially problematic since it depends on libraries whose tests are flapping (for instance I hit this one in [http-link](https://github.com/myfreeweb/http-link-header/issues/7)).

I tried putting `pkgs.haskell.lib.dontCheck` in front of all the deps in [addLibs](https://github.com/obsidiansystems/obelisk/blob/master/default.nix#L112-L125) but it still seemed to want to build with tests. Im hoping someone with more nix-foo could suggest a solution.

**Comment by madeline-os** [comment]
In the time since this issue was reported, our binary caching situation has improved. I am closing this issue on the faith that it is harder to get into a situation where obelisk is forced to build from scratch when the caches are properly configured.

I have created issue #924 to focus on ensuring that binary caches actually work during installation: When they don't work, we consider this a bug. We are reluctant to optimize the pleasantness of what we consider a failure mode.
