### ISSUE TITLE
`ob run` scanning the ~/.ghc dbs can result in conflicting dependencies

### ISSUE THREAD

**Issue by marcotoniut** [obsidiansystems/obelisk#207]
`ob run` was unable to solve a discrepancy between the `reflex-0.5` found in the `nix/store` and the one in `~/.ghc/x86_64-darwin-8.0.2/`

**Comment by ElvishJerricco** [comment]
We really ought to `-hide-all-packages` except the ones Nix gives us somehow.

**Comment by ryantrinkle** [comment]
Would this help? https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/packages.html#ghc-flag--no-user-package-db

**Comment by 414owen** [comment]
So this was most likely fixed by https://github.com/obsidiansystems/obelisk/pull/571.
Unfortunately, I've been unable to build an old enough obelisk on my system to reproduce this bug exactly, but I've run the current obelisk with a cabal-installed (clashing) version of dependent-map (0.3), and nothing seemed awry. If anyone manages to reproduce this, feel free to reopen the issue. It might be very environment-specific.

**Comment by 3noch** [comment]
Thanks!

**Comment by 3noch** [comment]
We also use `--pure` shells now for `ob run` which may be filtering more things out. I know I ran into issues without `--pure`.
