### ISSUE TITLE
"ob --help" should print the help immediately and not build anything

### ISSUE THREAD

**Issue by mightybyte** [obsidiansystems/obelisk#296]
The general expectation is that command-line tools return immediately when you pass `--help`.  This is not currently the case in obelisk.  It blocks for awhile on:

```
./.obelisk/impl: command not cached, building ...
```

This is pretty frustrating as a first impression.

**Comment by ryantrinkle** [comment]
That's because it's going to give you the help for the ob command specific
to your project, as opposed to your globally-installed Obelisk.  Perhaps we
could display something more meaningful to the user, e.g.:

`Setting up your project's 'ob' command`

We *could* also tell the user about `--no-handoff`, but I think it might
give people the wrong impression - `--no-handoff` is almost never the right
thing to do, including in this situation.

**Comment by mightybyte** [comment]
I'm sure there are good technical reasons why it works this way, but it's still not a great user experience.  I might suggest displaying the help message for the globally-installed Obelisk, notifying the user that it might be out of date, and forking off a background thread to build the project specific version.

**Comment by madeline-os** [comment]
We will investigate the root cause of this issue, which is the fact that evaluation of the project obelisk takes a long time and cannot be cached. Please see #926 for further developments.
