### ISSUE TITLE
Not rebuild application if same version already deployed.

### ISSUE THREAD

**Issue by eskimor** [obsidiansystems/obelisk#312]
Sometimes one only wants to do a deployment for changing some configuration, it would be nice if this were possible without re-building and downloading everything. This way the guy managing configs does not need to be a developer with a beefy machine, also the re-building is obviously not needed.

**Comment by 3noch** [comment]
I'm surprised that things get rebuilt in this situation. Nix should know how to not duplicate work. Or perhaps you mean: When someone *else* deploys, they shouldn't need to rebuild on their machine? In this case the target server would have to act as a cache?

**Comment by eskimor** [comment]
Right, that's what I mean. If  you have built it on your machine nothing gets rebuilt of course.

**Comment by eskimor** [comment]
Well I guess this could be implemented by having the server act as a cache I suppose (should obviously happen via ssh), yeah I guess this would make sense!

**Comment by 3noch** [comment]
I think you can already do this manually by using `nix-instantiate` on your deployment (you'd have to reconstruct the right command by looking at the verbose output of `ob deploy`). With that you could use `nix-copy-closure --include-outputs` from the server to your local machine.

**Comment by ryantrinkle** [comment]
There are two major issues with the idea of pulling build artifacts from the deployed servers.

1. The build machine should not trust the contents of the store on any deployed machine.  What if the deployed machines are ever hacked?  If the build machine is compromised, recovery will be very difficult.
2. The build machine should not be stealing resources - in this case download bandwith - from the production machines.  What if you're trying to deploy because you're underprovisioned and the system is therefore struggling?  The last thing you want to do is have the build machine start leaning on the production cluster.

Instead, I think we should make the build machine not lose the artifacts in the first place, e.g. by creating GC roots with nix.  Failing that, the build machine could pull from the CI machine.

**Comment by 3noch** [comment]
I definitely agree that using the target server as a cache and/or copying from it is not a good idea for default behavior. But I must confess I've wanted this several times before when I *knew* that the server wouldn't be adversely impacted. The use case has usually been a "quick fix" to some simple configuration, often to a staging server where I'm not as worried.

**Comment by ryantrinkle** [comment]
But why did your build server not have that stuff?

**Comment by 3noch** [comment]
I didn't have a build server :)

**Comment by 3noch** [comment]
Oh, but I suppose your question still applies for just my local machine. Cases I've run into before:

  * Using a different machine than the one I built on
  * Trying to deploy to an old server where I no longer had the cache
  * Using a VM for the builder and the VM was previously deleted (especially common on Mac)

**Comment by 3noch** [comment]
Examples of quick fixes I've wanted to do:

  * Change domain name
  * Change nginx rule
  * Change various configs (like SMTP settings, etc.)

**Comment by ryantrinkle** [comment]
I don't really have a problem with someone using nix-copy-closure in a situation like that, but I really would prefer if this were treated as more of an "emergency recovery" approach, not a recommended way of doing anything.

**Comment by 3noch** [comment]
Definitely agree.
