### ISSUE TITLE
`get` from Obelisk.ExecutableConfig should `strip` by default

### ISSUE THREAD

**Issue by vaibhavsagar** [obsidiansystems/obelisk#314]
I almost never see `get` without `T.strip` in front of it. Can we make this the default behaviour and perhaps provide a `getRaw` for those cases that need the full input with spaces?

**Comment by ryantrinkle** [comment]
I understand the impulse here, but I don't think the increased complexity of the semantics is worth the O(1) decrease in boilerplate (per file format - which are already bespoke).  Imagine, for example, trying to debug, while releasing to production, why your encryption key file won't load, because it happens to start or end with 0x20 or 0x0A.

Longer term: we should not be using raw text files - we should have some kind of format that we use that can be validated statically, and that doesn't allow these kinds of ambiguities to creep in.
