### ISSUE TITLE
ob deploy update has trouble with private repos

### ISSUE THREAD

**Issue by mightybyte** [obsidiansystems/obelisk#351]
When I run `ob deploy update` it fails with this error.

```
$ ob deploy update -v
Starting Obelisk </nix/store/j8wls8a89xr6s1a47lg6g83gnbdrfd0l-obelisk-command-0.1/bin/.ob-wrapped> args=["deploy","update","-v"] logging-level=Debug
Creating process: 'nix-build' './.obelisk/impl' '-A' 'command' '--no-out-link'
...
Initialized empty Git repository in /nix/store/...
Could not create directory '/home/mightybyte/.ssh'.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Could not create directory '/home/mightybyte/.ssh'.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Unable to checkout ... from ssh://git@github.com/....
builder for '/nix/store/...' failed with exit code 1
error: build of '/nix/store/...' failed
(use '--show-trace' to show detailed location information)
Process exited with code 1; 'nix-build' './.obelisk/impl' '-A' 'command' '--no-out-link'
✖ Running nix-build on ./.obelisk/impl [command]
```

I have verified that I can indeed clone the repo because this machine has an ssh key that has the appropriate permissions.

**Comment by alexfmpe** [comment]
I vaguely recall running into a similar issue half a year ago. 
IIRC, obelisk's git operations would simply fail in the case where directly running the git command would ask for my ssh pass phrase.
Since, I have `AddKeysToAgent yes` in my `.ssh/config`, the problem would only happen if I did some obelisk+git operation before ever running a git operation since the session started

**Comment by eskimor** [comment]
Passing `--no-handoff` fixed the issue. Investigating further a bit ...

**Comment by mightybyte** [comment]
There was no passphrase involved here.  I created a brand new ssh key, added it to my github account, and successfully cloned the private repo by hand.  So keys are categorically not the problem.  It seems to almost definitely be an obelisk thing.  And yes, for reasons that are still unknown passing `--no-handoff` did fix the issue.

**Comment by 3noch** [comment]
`ob deploy update` is just an alias for `ob thunk update src`. Is the repo hosted on GitHub? Obelisk can clone private repos from GitHub AFAIK.

**Comment by mightybyte** [comment]
Yes, the repo is hosted on github.

**Comment by ryantrinkle** [comment]
OK, it looks like this is due to our github-specific fetching infrastructure losing support for private repos.  The workaround seems to be:
```
ob thunk unpack src
ob thunk pack src
```
This will convert `src` from github thunk to a regular git thunk.
I don't think we have a good way to add that github-specific private fetching support back in the near future, so this is the way to go for now.  (The very long-term solution would be to use OAuth2 and the github API.)

**Comment by eskimor** [comment]
Actually, that was the first thing I checked: He had a `.git.json` already. So I don't think this is the same issue.

**Comment by 3noch** [comment]
I would expect that you actually *want* to have a `github.json` since that's the thunk which will use `fetchFromGitHub` and hence use GitHub-specific features to talk to private repos. On the nix side it will use the appropriate environment variables to use your user's keys to fetch.

**Comment by JBetz** [comment]
I ran into the same issue with a private gitlab repo, and was able to get it working it by modifying `src/default.nix` in the deployment repo to use `fetchgitPrivate` instead of `fetchgit`, running `ob deploy update` once, switching it _back_ to `fetchgit` afterwards, then running it again.

So it looks like there's some system state that isn't being captured by nix that's required for private repos, and error messages point to ssh known hosts.

**Comment by ryantrinkle** [comment]
@JBetz For a fixed-output derivation (like fetchgit*), once you have anything in you nix store with the correct hash, it won't try to download/build/whatever it again, even if you make changes to the derivation.  So, switching it back to fetchgit afterwards should not have had any effect (and it sounds like it didn't).

We do have logic that is meant to detect when a repo is private, but it sounds like that logic is not working correctly.

**Comment by JBetz** [comment]
@ryantrinkle Okay, makes sense. 

So to correct what I said earlier, switching back to `fetchgit` is necessary so you can run `ob deploy push` without obelisk blocking you because of a modified `default.nix`, but there's no point in running `ob deploy update` again.

And FYI, none of the other workarounds mentioned in this thread worked for me.
