### ISSUE TITLE
How to extract flags used to make GHCi session?

### ISSUE THREAD

**Issue by mpickering** [obsidiansystems/obelisk#363]
I want to add support to `haskell-ide-engine` for obelisk. 

In order to do this I just need the list of flags used to invoke `ghci` when `ob run` is called.

My ideal interface is that there is a command I can run (for example `ob get-args common/Foo.hs`) which will output the list of flags such that `ghci $(ob get-args common/Foo.hs) common/Foo.hs` will succeed. 

I haven't yet looked into the internals of obelisk so a little bit of direction might be all I need to implement this. I've already implemented support for `cabal`, `hadrian` and `rules_haskell`.

**Comment by eskimor** [comment]
Alternatively, "just" linking with obelisk-command would give you access to that function. Don't know if this is an option.

**Comment by mpickering** [comment]
Thanks for your prompt reply @eskimor 

Right, linking is not an option. `withGhcCmd` looks like what I need but it seems that some arguments that should appear on the command line are in the script.

Would it be appropriate to refactor `withGhciScript` so that the continuation is of type `([String], FilePath) -> m ()` so that the first component of the tuple is the command line arguments and the second is the `.ghci` file? That way I could easily implement a target which dumped out the necessary command line.

I was also wondering that there is no call to `-package-db`, where is the package database? Perhaps there is something funny going on with `-i` in the script.

**Comment by 3noch** [comment]
The package db is generated by nix ultimately via `ghcWithPackages`.

**Comment by benkolera** [comment]
@mpickering The way that I go about this is to wrap up the commands that are being run in a nix-shell. 

In my current emacs setup, that actually means running hie in a nix shell, running a separate hie for backend/common/frontend. Like so:

`nix-shell -I . --arg hie true --command hie-wrapper --lsp -d -l /tmp/hie.log /home/bkolera/src/github/qfpl/reflex-realworld-example/frontend` . This is done by having a shell.nix next to the cabal file that is `import (../.).shells.ghc` to get the right haskell environment in the shell. 

This way, hie just runs individually for each cabal file, but it's not entirely idea. I end up having to create a sandbox for each cabal file and add-sourcing common so that they play nice. It's not ideal and can get pretty flakey with the slower than normal compile times in obelisk land, but my setup may help you a little (or at least not hurt), perhaps! :slightly_smiling_face:

**Comment by mpickering** [comment]
Thanks @benkolera 

I implemented prototype support for this on my branch - https://github.com/mpickering/obelisk/tree/ide-args

It worked with the example project you linked above (after launching vscode from the shell). There is a problem with `TemplateHaskell` and `jsaddle-dom` seeming to hang whilst loading. I don't have time to investigate that now but support for obelisk should definitely be possible in future once we work that out. It is probably just setting some options incorrectly.

**Comment by 3noch** [comment]
Note that we can get the pkg database directly: ```cat "$(nix-build -E '(import <nixpkgs> {}).haskellPackages.ghcWithPackages (p: [p.vector])' --no-out-link)"/bin/ghci
#! /nix/store/cinw572b38aln37glr0zb8lxwrgaffl4-bash-4.4-p23/bin/bash -e
export NIX_GHC='/nix/store/i512zr3700xrc9d6aapjwqa1hxgj53kl-ghc-8.6.4-with-packages/bin/ghc'
export NIX_GHCPKG='/nix/store/i512zr3700xrc9d6aapjwqa1hxgj53kl-ghc-8.6.4-with-packages/bin/ghc-pkg'
export NIX_GHC_DOCDIR='/nix/store/i512zr3700xrc9d6aapjwqa1hxgj53kl-ghc-8.6.4-with-packages/share/doc/ghc/html'
export NIX_GHC_LIBDIR='/nix/store/i512zr3700xrc9d6aapjwqa1hxgj53kl-ghc-8.6.4-with-packages/lib/ghc-8.6.4'
exec "/nix/store/8vq01xmxlp9wxzilkw85rb621ag7nwmd-ghc-8.6.4/bin/ghci"  "-B$NIX_GHC_LIBDIR" "${extraFlagsArray[@]}" "$@"```

**Comment by madeline-os** [comment]
I'm closing this as the motivating use-case, haskell-ide-engine, has been supplanted by HLS. HLS integration is on our roadmap. Anyone that still has a use-case is welcome to make another issue.
