### ISSUE TITLE
Could not deduce: MonadJSM from performRequestAsync

### ISSUE THREAD

**Issue by clojurians-org** [obsidiansystems/obelisk#367]
it seems performRequestAsync function can't be supported on server side.
so what's the right way to call rest api server?

the code and the exception attached:
```
larrys-MBP:test larluo$ cat frontend/src/Frontend.hs 
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE RecursiveDo #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE DeriveGeneric       #-}

module Frontend where

import qualified Data.Text as T
import Obelisk.Frontend
import Obelisk.Route
import Reflex.Dom.Core

import Common.Api
import Common.Route
import Obelisk.Generated.Static

import Data.Map (Map)
import qualified Data.Map as Map
import Data.Maybe (fromMaybe)
import Control.Monad.Fix (MonadFix)

checkedState :: Bool -> T.Text
checkedState True = "Checkbox is checked"
checkedState _    = "Checkbox is not checked"

buildReq :: T.Text -> XhrRequest ()
buildReq code = XhrRequest "GET" ("https://opendata.netcetera.com/smn/smn/" <> code) def

stations :: Map.Map T.Text T.Text
stations = Map.fromList [("BIN", "Binn"), ("BER", "Bern"), ("KLO", "Zurich airport"), ("ZER", "Zermatt"), ("JUN", "Jungfraujoch")]

bodyElement :: (DomBuilder t m, MonadFix m, MonadHold t m, PostBuild t m) => m ()
bodyElement = el "div" $ do
  el "h2" $ text "Swiss Meteo Data (raw version)"
  text "Choose station: "
  dd <- dropdown "BER" (constDyn stations) def
  -- Build and send the request
  evStart <- getPostBuild
  let evCode = tagPromptlyDyn (value dd) $ leftmost [ () <$ _dropdown_change dd, evStart]
  evRsp <- performRequestAsync $ buildReq <$> evCode
  -- Display the whole response
  el "h5" $ text "Response Text:"
  let evResult = (fromMaybe "" . _xhrResponse_responseText) <$> evRsp
  dynText =<< holdDyn "" evResult
  return ()

frontend :: Frontend (R FrontendRoute)
frontend = Frontend
  { _frontend_head = do
      el "title" $ text "Obelisk Minimal Example"
  , _frontend_body = bodyElement

  }
```

```
frontend/src/Frontend.hs:42:12-52: error:
    • Could not deduce (Language.Javascript.JSaddle.Types.MonadJSM
                          (Performable m))
        arising from a use of ‘performRequestAsync’
      from the context: (DomBuilder t m, MonadFix m, MonadHold t m,
                         PostBuild t m)
        bound by the type signature for:
                   bodyElement :: forall t (m :: * -> *).
                                  (DomBuilder t m, MonadFix m, MonadHold t m, PostBuild t m) =>
                                  m ()
        at frontend/src/Frontend.hs:34:1-81
    • In a stmt of a 'do' block:
        evRsp <- performRequestAsync $ buildReq <$> evCode
      In the second argument of ‘($)’, namely
        ‘do el "h2" $ text "Swiss Meteo Data (raw version)"
            text "Choose station: "
            dd <- dropdown "BER" (constDyn stations) def
            evStart <- getPostBuild
            ....’
      In the expression:
        el "div"
          $ do el "h2" $ text "Swiss Meteo Data (raw version)"
               text "Choose station: "
               dd <- dropdown "BER" (constDyn stations) def
               evStart <- getPostBuild
               ....
   |
42 |   evRsp <- performRequestAsync $ buildReq <$> evCode
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by benkolera** [comment]
If you change body element from

bodyElement :: (DomBuilder t m, MonadFix m, MonadHold t m, PostBuild t
m) => m ()

bodyElement = el "div" $ do

to

bodyElement :: (DomBuilder t m, MonadFix m, Prerender js m, MonadHold
t m, PostBuild t m) => m ()

bodyElement = prerender (text "Loading...") $ el "div" $ do


That should work. With the new server rendering, you need to wrap up
elements that require JS in a prerender so that the server can render the
non-JS version first.

**Comment by clojurians-org** [comment]
thanks, it works now.

bodyElement :: (DomBuilder t m, MonadFix m, Prerender js m, PerformEvent t m, TriggerEvent t m, MonadHold t m, PostBuild t m) => m ()

bodyElement = prerender (text "Loading...") $ el "div" $ do

**Comment by ryantrinkle** [comment]
@clojurians-org @benkolera FYI, wrapping your whole app in `prerender` will have a big downside: your user will have to wait for the app to load before they can see anything.  Normally, obelisk apps are rendered server-side so that the user can see the app instantly, before the JS has actually loaded.

To get the best of both worlds, wrap *only the thing that really needs to use MonadJSM* in prerender, and leave the rest of your app outside it.  That way, only a small loading widget will be shown, but the rest of the page will remain server-side rendered.

**Comment by benkolera** [comment]
Yeah, sorry for the vague and potentially harmful quick email help there, @ryantrinkle ! 

As an aside, are the things in Reflex.Dom.Widget.Input going to be able to drop their constraint on forcing a GhcjsDomSpace? I find myself needing much bigger prerenders than I probably should because of of forms.

**Comment by ryantrinkle** [comment]
Reflex.Dom.Widget.Input will largely be deprecated in favor of more direct
use of inputElement and perhaps some simpler wrappers. We do need to make
sure all the same functionality is still available, though.
