### ISSUE TITLE
Static site generator using obelisk

### ISSUE THREAD

**Issue by Rizary** [obsidiansystems/obelisk#425]
Every javascript framework has its own way to build static site. They simply use npm packages, like [marked](https://www.npmjs.com/package/marked) or [highlight.js](https://www.npmjs.com/package/highlight.js). Since we have pandoc and also I remember seeing @dalaing work which utilize `Static` (or `Obelisk.Generated.Static`) and `Pandoc`, is there any plan to make it easier for user who want to build static site using obelisk?

**Comment by 3noch** [comment]
Thanks for asking! There are no plans to do this. If you have any *specific* ideas please open as new issues/PRs.

**Comment by anka-213** [comment]
This project seems to try be an attempt at solving this problem: https://github.com/srid/reflex-stone

**Comment by kmicklas** [comment]
I recently converted an Obelisk site (which was previously dynamic but no longer needs to be) to be static with a simple executable and Nix derivation. I'll paste the relevant snippets here.

```haskell
main :: IO ()
main = do
  for_ staticRoutes \route -> do
    html <- renderFrontendHtml mempty mempty encodeFrontendPath route frontend blank blank
    let path = makeRelative "/" $ T.unpack $ encodeFrontendPath route
    let filePath = if ".html" `T.isSuffixOf` (T.pack path)
          then path
          else path </> "index.html"
    createDirectoryIfMissing True $ takeDirectory filePath
    BS.writeFile filePath html
```

The exact way the `.html` paths are created may depend on what static hosting system you're using.

The Nix derivation just runs this binary, which is added as an Obelisk package in `default.nix`:

```nix
let
  obelisk = import ./. {};

in obelisk.obelisk.nixpkgs.stdenv.mkDerivation {
  name = "static-site";
  dontUnpack = true;
  buildPhase = ''
    mkdir -p $out/static
    cd $out
    ${obelisk.ghc.generate-static}/bin/generate-static
    cp -r ${obelisk.passthru.processedStatic.symlinked}/* $out/static/
  '';
  dontInstall = true;
}
```

If someone is interested, this could probably be abstracted to be reusable since the only way it really depends on the project details is via `staticRoutes`.
