### ISSUE TITLE
Hydration fails with implied elements e.g. tbody

### ISSUE THREAD

**Issue by jhartzell42** [obsidiansystems/obelisk#441]
If you take peg solitaire:
https://github.com/reflex-frp/reflex-examples/blob/2dd35b80946ffbe81b07965c5f9e8dafc098afea/frontend/src/Frontend/Examples/PegSolitaire/Main.hs
And copy-and-paste it into a fresh Obelisk project, Hydration fails, because it contains a table. In the HTML we send the browser, it generates a tbody, but we don't generate a tbody in the other version, so the switchover fails.
Can be fixed by adding a tbody here:
https://github.com/reflex-frp/reflex-examples/blob/2dd35b80946ffbe81b07965c5f9e8dafc098afea/frontend/src/Frontend/Examples/PegSolitaire/Main.hs#L153
But I think there should be either a clearer error or better support for implied tags.

**Comment by jhartzell42** [comment]
(For whatever reason, I can't reproduce in reflex-examples itself, but rather by copying the Main.hs from PegSolitaire into a fresh Obelisk project)

**Comment by tomsmalley** [comment]
The reason it doesn't happen in `reflex-examples` is because the version of obelisk it points to is pre-hydration, so it just replaces the entire page

**Comment by ApolloUnicorn** [comment]
> The reason it doesn't happen in `reflex-examples` is because the version of obelisk it points to is pre-hydration, so it just replaces the entire page

@Ericson2314 is this still accurate?

**Comment by ohri-anurag** [comment]
I tried the above steps, and I have the following observations:
1. The examples work fine in the [reflex-examples](https://github.com/reflex-frp/reflex-examples) repo, after running `ob run`.
2. I followed the steps below while copying the Peg Solitaire version over to a new Obelisk project, that I had created by running `ob init`.
  a. I copied the contents of the file [Main.hs](https://github.com/reflex-frp/reflex-examples/blob/master/frontend/src/Frontend/Examples/PegSolitaire/Main.hs) in Peg Solitaire, except for the pragmas and module imports.
  b. I pasted these contents in my new project's `frontend/src/Frontend.hs` at the end of the file.
  c. I added the necessary pragmas and module imports to get the code to run, using `ob run`.
  d. I copied over the static assets [directory](https://github.com/reflex-frp/reflex-examples/tree/master/static/peg-solitaire), and pasted it inside the new project's static directory. To be clear, I copied the entire `peg-solitaire` directory inside `static` folder, and not just its contents.
  e. Finally, I added a `prerender_ blank $` to the definition of the `app` function, along with the required typeclass constraint. it now looks like:
```haskell
app
  :: ( DomBuilder t m
     , MonadFix m
     , MonadHold t m
     , PostBuild t m
     , Prerender t m
     )
  => m ()
app = prerender_ blank $ divClass "container" $ do
  el "br" blank
  elAttr "h1" ("style" =: "text-align: center") $ text "PEG SOLITAIRE"
  el "div" $ do
    el "br" blank
    el "div" $ do
      rec
        gs  <- foldDyn move initialState pos
        pos <- mkBoard gs
        elAttr "h3" ("style" =: "text-align: center") $
          dynText $ fmap (\g -> "Score: " <> (T.pack . show . score) g) gs
      return ()
```

After performing all these steps, the Peg Solitaire example started working in the new project.

If you look closely, you'll see that in `reflex-examples`, the [examples](https://github.com/reflex-frp/reflex-examples/blob/3c1b7096e22675b5ea6abb0271ad11544cbc9122/frontend/src/Frontend.hs#L58) function has a `Prerender t m` constraint. This is required by Drag and Drop, I think it is needed by all the other examples too, but since it is applied to one, it might be doing the same for all the examples.
