### ISSUE TITLE
Updating after to a new version of obelisk

### ISSUE THREAD

**Issue by ruhatch** [obsidiansystems/obelisk#455]
I'm just getting started with my first `obelisk` application, but I'm concerned about keeping the template provided by `ob init` in sync as changes are made upstream. Are there any plans in place for some sort of `ob init --update` or similar that will might allow diffing your current project structure against the new template. I'm hoping for something similar to spacemacs' config synchronising functionality.

**Comment by ali-abrar** [comment]
That's a good idea. Currently, no such facility is in place. We have been trying to ensure that all API changes are documented in the changelog to make upgrading easier, but some other form of migration assistance would be good. I'll have a look at how spacemacs does it.

**Comment by madeline-os** [comment]
Hi, since this issue was filed, I believe that we have made it much easier to understand what is changing from version to version. Figuring out the changes to the template app (which we call [skeleton](https://github.com/obsidiansystems/obelisk/tree/master/skeleton)) and how they affect user projects would be very tricky in code.

I hope that it suffices as a solution to diff the skeleton project from obelisk version to obelisk version, so that you can figure out how your project can benefit from new features and bug fixes.

For _breaking changes_, our policy is that we must provide a migration guide. If you experience a regression while upgrading obelisk, please file an issue!
