### ISSUE TITLE
Is there a way to create a deployment locally?

### ISSUE THREAD

**Issue by dalaing** [obsidiansystems/obelisk#58]
I'm playing around with Obelisk and wanted to check the size of the output js.  I couldn't find anything in the ob thunk or ob deploy options that let me get hold of the output of a project built using obelisk, unless I actually set up a server to deploy the project to.  

I don't have a pressing business need for this, I mostly just want it to be able to locally debug a few steps in my workflow.

Am I missing something? Is Obelisk missing something? Or is there magic going on under the hood that should be hidden from the users?  Hiding magic from users is a good thing, so I'm fine if that's the case :)

**Comment by srid** [comment]
Looking at the code I _think_ we can do it by exposing [`serverExe`](https://github.com/obsidiansystems/obelisk/blob/6f856f4/default.nix#L161-L171) from default.nix to Obelisk projects somehow.

**Comment by 3noch** [comment]
I noticed this as well. Nixops has some options for `deploy` like `--copy-only` and `--build-only`. `--build-only` builds all derivations and then stops. `--copy-only` also copies them to the server but does not switch the configuration. I think we need to add options like this, especially since they can help make time-sensitive deployments go better (e.g. you can ensure everything is built and copied before you officially start a scheduled down time).

**Comment by srid** [comment]
I gave this a stab in #61. 

Something fundamentally different is happening when you run the server _locally_; it seems that `getAssetPath` is returning a Nothing, which means that we cannot serve `all.js` successfully. Need to see what's going on ...

**Comment by ali-abrar** [comment]
This is covered in the readme now: https://github.com/obsidiansystems/obelisk#locally
