### ISSUE TITLE
Allow thunks to refer to sources without default.nix

### ISSUE THREAD

**Issue by 3noch** [obsidiansystems/obelisk#601]

**Comment by Ericson2314** [comment]
Once implication of this is we might not want to use a auto-generated `default.nix` because when the thunk is unpacked, there won't be a repo-provided default.nix. We could say this is *only* for repos that don't provide a default.nix, in which case nothing will overwrite the `default.nix`, but I rather this sort of thunk be a foundation for everything else, and thus have it work whether or not there is a `default.nix` in the repo. In that case, the user would basically decide whether to e.g. `hackGet ./dep/foo` or  `import (hackGet ./dep/foo)`, and the `hackGet`-ing works the same either way.

**Comment by 3noch** [comment]
Good point. So goals are:

* `hackGet` (or similar) has same interface for repos with default.nix and repos without default.nix
* `import dep/foo {}` works only for repos with default.nix and fails at evaluation-ish time for repos without it

As usual, packedness has no effect (other than of course the obvious effects of passing through some fetcher, etc).

Does this sound right to you?

**Comment by Ericson2314** [comment]
Exactly right.

**Comment by 3noch** [comment]
@xplat and I came up with a plan for this:

Add a new file to the thunk directories (maybe `source.nix` or `src/default.nix`) which does everything that the `default.nix` loader does *except* importing the `default.nix` in the thunked source. Change `default.nix` to merely do the "double import" for this.

Make `source.nix` look for a sibling directory (with a short name like `_`) which may house a checkout of the source. If such a directory exists, the `source.nix` should use that instead of loading from `git.json`/`github.json`/etc.

Make `ob thunk unpack` simply unpack to the `_` directory in the thunk. It doesn't need to keep the old thunk meta-info in the unpacked repo's `.git` either since that is now easily available.

Make `ob thunk pack` simply update the `git.json`/`github.json` files and loader as it normally does and then delete the unpacked directory. It could even *move* the unpacked dir to a different name as a way of not losing things, but that's another idea for another time.

What this accomplishes:

All thunks now have a `default.nix` which is backward compatible with previous usage (`import ./dep/thunk` works the same way). However, it *additionally* supports traditional `hackGet` use cases without actually needing `hackGet` at all. You now just use `import ./dep/thunk/source.nix` instead of `hackGet ./dep/thunk`.

**Comment by madeline-os** [comment]
If I am not mistaken, this is implemented. I'm pretty sure I have used this feature myself. Let me know if I am mistaken.
