### ISSUE TITLE
Server-side rendering (prerender) testing workflow

### ISSUE THREAD

**Issue by Lermex** [obsidiansystems/obelisk#699]
Say I want to make sure my Obelisk website is fully usable is prerender mode without javascript, including being able to navigate between pages. What's the recommended workflow for testing in this mode?

Ideally, I imagine something like `ob run --only-server`. Is it worth implementing something like that?

**Comment by alexfmpe** [comment]
Is disabling javascript in the browser's devtools enough for your purposes?

**Comment by ryantrinkle** [comment]
There's not currently a special mode for testing that, but I would recommend disabling JS in your browser and testing like that; that's worked well for me in the past.

The main thing is that you need to use real `href`s in your `a` tags; make sure to generate those using RouteToUrl rather than writing them out by hand - then you can be sure they stay correct as your URL schema changes.

**Comment by madeline-os** [comment]
I will make sure that these suggestions are recorded in the FAQ. Thank you for the request.
