### ISSUE TITLE
Error with nix-build during "ob deploy push"

### ISSUE THREAD

**Issue by reubenharry** [obsidiansystems/obelisk#833]
I'm working on macOS Catalina.

I'm using the calculator tutorial repo as an example project: https://github.com/obsidiansystems/calculator-tutorial and am following the "deploying" instructions on https://github.com/obsidiansystems/obelisk.

When I run "ob deploy push", from calculator-tutorial/calculator-tutorial-deploy, I get (eventually):

error: hash mismatch in file downloaded from 'https://github.com/NixOS/nixpkgs-channels/archive/nixos-19.09.tar.gz':
  wanted: sha256:0ysb2017n8g0bpkxy3lsnlf6mcya5gqwggmwdjxlfnj1ilj3lnqz
  got:    sha256:157c64220lf825ll4c0cxsdwg7cxqdx4z559fdp7kpz0g6p8fhhr
(use '--show-trace' to show detailed location information)
Process exited with code 102; 'nix-build' '/Users/reuben/calculator-tutorial/calculator-tutorial-deploy/src' '-A' 'server.system' '--argstr' 'hostName' 'ec2-3-90-207-72.compute-1.amazonaws.com' '--argstr' 'adminEmail' 'reubencg@ec2-3-90-207-72.compute-1.amazonaws.com' '--argstr' 'routeHost' 'ec2-3-90-207-72.compute-1.amazonaws.com' '--argstr' 'version' '2636a4c134f5de3379e0aeea54507c9eea3d18ef' '--arg' 'enableHttps' 'true' '--builders' 'obelisk-docker-nix-builder x86_64-linux /Users/reuben/.local/share/obelisk/nix-docker-builder/id_ed25519_obelisk_vm 1 1 kvm' '--no-out-link'
✖ Running nix-build on /Users/reuben/calculator-tutorial/calculator-tutorial-deploy/src [server.system]

I've encountered this problem on two separate macOS Catalina systems.

**Comment by madeline-os** [comment]
Hi. This issue is proving difficult to reproduce. I am working on making our MacOS support more responsive and robust so that we can jump as these issues as soon as they happen. I am closing this issue with the hope that it either has been resolved, or will be obviated by the larger push on MacOS stability we are doing.

If this issue is still causing you grief, please re-open it, and we can work together to diagnose it.
