### ISSUE TITLE
Use ngrok in development

### ISSUE THREAD

**Issue by stevekrouse** [obsidiansystems/obelisk#841]
I'd like to be able to run `ob run` in one shell and point `ngrok` at it. When I do this currently, it works up until it tries to do any jsaddle stuff, and then I get the following errors because these URL's referncing localhost instead of the ngrok URL:

![Screen Shot 2021-02-17 at 4 18 09 PM](https://user-images.githubusercontent.com/2288939/108269331-d249e780-713b-11eb-8932-c82f6642eb2a.png)
![Screen Shot 2021-02-17 at 4 18 02 PM](https://user-images.githubusercontent.com/2288939/108269333-d2e27e00-713b-11eb-9ccf-994d141c0779.png)

One solution that would work for me is simply hardcoding the URL to what I want it to be. Another is pulling it from the browser locally via `window.location` in jsaddle.js.

However, I don't know how I'd modify jsaddle.js and get those edits to take hold in my project. Any suggestions? Thanks!

When I tried editing `config/common/route`, I got an error.

**Comment by ryantrinkle** [comment]
@stevekrouse Did you try setting [`config/common/route`](https://github.com/obsidiansystems/obelisk/blob/master/skeleton/config/common/route) to `"https://mysite.ngrok.io/jsaddle"`?

**Comment by stevekrouse** [comment]
I think so but I forget. I will give that another try, thanks!

**Comment by ryantrinkle** [comment]
@stevekrouse Any luck?

**Comment by stevekrouse** [comment]
Haven't been using ngrok actually so haven't tested this

**Comment by madeline-os** [comment]
I am closing this, but feel free to reopen if you start using ngroq again.

**Comment by augyg** [comment]
Seconding this, would make android development a lot easier

Going to look for a cheap fix

**Comment by alexfmpe** [comment]
@augyg if you're trying to use the `jsaddle-warp` flow on your android via `ob run`, you can replace `localhost` with your wlan IP or what-have-you in `config/common/route` and then open that IP on the phone's browser.

**Comment by augyg** [comment]
@alexfmpe yes but its more of an ergonomic issue because if you do that then the backend will try to bind on the ngrok route and fail with runWidget: socket.bind permission denied, so I've just been changing the route to the ngrok route to build android and then switching it back to localhost:8000

So it's not that big a deal, but I would just like to have a lazier solution.

I'm also noticing that there's some nuance to cookies with android apps in local development since this would technically be a 3rd party request, and even if I did this switching back and forth I would be unable to set a cookie through a Set-Cookie header if I was to read in config/common/route, since this would be http://localhost:<PORT> and so the Set-Cookie could not declare certain options that are necessary for cross-origin requests. So it would be nice to grab `config/common/route` and set the cookie for the domain, which should be ngrok not localhost.

**Comment by augyg** [comment]
So with my understanding of the problem, I think it would be simplest to have a config file `config/common/ngrokroute` with a value like localhost:8000 that is passed to[ runWidget ](https://github.com/obsidiansystems/obelisk/blob/135bfd7422b856c146b5cd5dacfe584f0621825e/lib/run/src/Obelisk/Run.hs#L182-L188)

if and only if the value of the host of config/common/route is ngrok-free.app

Since we would always want to runWidget on some localhost route in development, including when the value of `config/common/route` is ngrok
