### ISSUE TITLE
ob run reads both package.yaml and corresponding generated .cabal resulting in warnings

### ISSUE THREAD

**Issue by dimsmol** [obsidiansystems/obelisk#882]
Obelisk version: `v0.9.1.0`
I've added `package.yaml` files to my project and use `hpack` to generate `*.cabal` files (mostly to avoid manually listing my modules).

`ob run` started to print warnings like this for all three packages (`backend`, `frontend`, `common`):
```
Packages named 'backend' appear in 2 different locations: 
  [Chosen] /path/to/project/backend/package.yaml
  [Chosen] /path/to/project/backend/package.yaml
```

Note that the warning mistakenly mentions the same location twice (I would expect one location for `package.yaml` and another for `*.cabal` instead).

If I remove either `package.yaml` or the corresponding `*.cabal` file, the warnings disappear.

An easy workaround is just to remove `*.cabal` files and rely on `package.yaml` but I may want to keep cabal files for some tooling that doesn't understand `package.yaml`.

**Comment by mankyKitty** [comment]
Obelisk leans on `callCabal2nix` and similar functions to read the required build information. In the presence of both a `package.yaml` and a `.cabal` file it will arbitrarily choose one as the source of truth. In this case it's chosen the `.yaml`. The warnings you're seeing are because it's detecting the duplication prior to making that decision. It should still work because it doesn't try to combine the two, it'll pick one and carry on.
